version: "2.13"
services:
  mio_webserver:
    build: .
    ports:
      - 8080:80
      - 8043:443
    volumes: 
      - ./all:/var/www/html/
  miodb:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=teriaca

  mio_phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8081:80
    environment:
    - PMA_ARBITRARY=1